var vh=window.innerHeight*0.01;document.documentElement.style.setProperty('--vh',vh+'px');window.addEventListener('resize',function(){var vh=window.innerHeight*0.01;document.documentElement.style.setProperty('--vh',vh+'px');});(function($){'use strict';if($("body").hasClass('home-page')){window.onbeforeunload=function(){window.scrollTo(0,0);}}
$(function(e){var fullpage_api;var responsiveWidth=1199;let projectSlide;if($(".feature-project-slide").length>0){$(".feature-project-slide").each(function(index,el){projectSlide=new Swiper(this,{loop:true,speed:1000,slidesPerView:1,spaceBetween:10,autoHeight:true,autoplay:{disableOnInteraction:true,delay:5000},pagination:false,navigation:{nextEl:$(".swiper-button-next",$(this).parent()).get(0),prevEl:$(".swiper-button-prev",$(this).parent()).get(0)},});projectSlide.autoplay.stop();});}
if(!$("body").hasClass('disable-fullpage')){var menu=$("#fullpageMenu").length>0?"#fullpageMenu":false;var sections=$("#fullpage > section");if(menu&&sections.length>0){var navIndex=0;$.each(sections,function(index,val){var title=$(this).data("title");var anchor=$(this).data("anchor");var addnav=$(this).data("nav");if((addnav===undefined||addnav===true)&&anchor&&anchor!=""&&title&&title!=""){navIndex++;var num=('0'+(navIndex)).slice(-2);$(menu).append("<li data-menuanchor='"+anchor+"' ><a href='#"+anchor+"'><span class='title'>"+title+"</span></a></li>");}});}
var scrollReady=false;if($("body").hasClass("ready")){scrollReady=true;}
fullpage_api=$('#fullpage').fullpage({sectionSelector:'section',onLeave:function(index,nextIndex,direction){if(sections[nextIndex-1]){const container=$(sections[nextIndex-1]);if(container.hasClass('animateOnce')&&container.hasClass('animated-done')){return;}
$(".animated",sections[nextIndex-1]).removeClass('go');}
if(nextIndex===3){setTimeout(()=>{projectSlide.autoplay.start();},1000)}},afterLoad:function(origin,destination,direction){$("body").addClass("show-nav");if(sections[destination-1]){$(sections[destination-1]).addClass('animated-done')
$(".animated",sections[destination-1]).addClass('go');}
var triggerFunction=$(sections[destination-1]).data("triggerfunction");if(triggerFunction!==undefined&&typeof(window[triggerFunction])==="function"){if(destination==1&&page_firsttime_load){setTimeout(function(){window[triggerFunction]();},2000);}else{window[triggerFunction]();}}
var scrollVideoStatus=false;if(scrollVideoStatus===false&&$("#bgvid").length>0){if($(sections[destination-1]).attr("id")=="section_video"){var video=$(".swiper-slide-active #bgvid");if(video.paused==true){video.play();jQuery(".bgvideo").addClass("d-none");jQuery(sections[destination-1]).addClass("video-status-play");scrollVideoStatus=true;}}}
if(menu){var addnav=$(sections[destination-1]).data("nav");if(addnav===undefined||addnav===true){$(".fullpage-nav-wrapper").addClass('show');}else{$(".fullpage-nav-wrapper").removeClass('show');}}},afterRender:function(){},scrollOverflow:true,responsiveWidth:responsiveWidth,lockAnchors:true,menu:menu});}
$("#fullpageMenu a, .btn-scroll").click(function(event){var link=$(this).attr('href');if(link.charAt(0)=="#"){var anchor=link.substring(1);if($('section[data-anchor="'+anchor+'"]').length>0){console.log($('section[data-anchor="'+anchor+'"]').length)
if(!$("body").hasClass('disable-fullpage')){var index=$("#fullpage > section").index($('section[data-anchor="'+anchor+'"]'));return $.fn.fullpage.moveTo(index+1);}}}else if($(this).not("a")&&$(this).attr("href")){console.log('redirect',$(this).attr("href"))
return window.location.href=$(this).attr("href");}
if($("body").hasClass("home")){return fullpage_api.moveTo(2,3);}else{return $("html, body").animate({scrollTop:0},1000);}
return false;});$(".js__toggle-menu").click(function(){var timeOut=$(window).width()>991?500:50;$("body").toggleClass("menu-open");if($("body").hasClass("menu-open")){$(".js__toggle-menu > span").html(window.translates.close);setTimeout(function(){$("body").addClass('opened');},timeOut);}else{$(".js__toggle-menu > span").html("Menu");setTimeout(function(){$("body").removeClass('opened');},timeOut);}
return false;});$(".js-accordion").click(function(event){if($("ul",this).length>0){$(this).toggleClass("open");return false;}});if($(".awards-slide").length>0){$(".awards-slide").each(function(index,el){var swiper=new Swiper(this,{loop:true,speed:1000,slidesPerView:1,spaceBetween:10,pagination:false,autoHeight:true,autoplay:{delay:5000,pauseOnMouseEnter:true},navigation:{nextEl:$(".swiper-button-next",$(this).parent()).get(0),prevEl:$(".swiper-button-prev",$(this).parent()).get(0)},});});}
if($(".news-slide").length>0){$(".news-slide").each(function(index,el){var swiper=new Swiper(this,{loop:true,speed:1000,slidesPerView:2,spaceBetween:20,pagination:false,navigation:{nextEl:$(".swiper-button-next",$(this).parent()).get(0),prevEl:$(".swiper-button-prev",$(this).parent()).get(0)},breakpoints:{768:{slidesPerView:3,spaceBetween:10,},}});});}
if($(".utilities-slide").length>0){$(".utilities-slide").each(function(index,el){var swiper=new Swiper(this,{loop:true,speed:1000,slidesPerView:1.2,spaceBetween:10,pagination:false,navigation:{nextEl:$(".swiper-button-next",$(this).parent()).get(0),prevEl:$(".swiper-button-prev",$(this).parent()).get(0)},breakpoints:{1200:{slidesPerView:2.3,},}});});}
if($(".project-slide").length>0){$(".project-slide").each(function(index,el){new Swiper(this,{loop:true,speed:1000,slidesPerView:1,spaceBetween:10,breakpoints:{768:{slidesPerView:1.5,slidesPerGroup:1,spaceBetween:20},1200:{slidesPerView:2.5,slidesPerGroup:1,spaceBetween:35},}});});}
if($(".events-slide").length>0){$(".events-slide").each(function(index,el){var swiper=new Swiper(this,{loop:true,speed:1000,slidesPerView:1.4,spaceBetween:10,pagination:false,navigation:{nextEl:$(".swiper-button-next",$(this).parent()).get(0),prevEl:$(".swiper-button-prev",$(this).parent()).get(0)},breakpoints:{1200:{slidesPerView:2.4},}});});}
if($(".partner-slide").length>0){$(".partner-slide").each(function(index,el){var swiper=new Swiper(this,{speed:1000,slidesPerView:2,grid:{rows:2,fill:'row'},autoplay:{delay:5000},spaceBetween:10,pagination:false,navigation:{nextEl:$(".swiper-button-next",$(this).parent()).get(0),prevEl:$(".swiper-button-prev",$(this).parent()).get(0)},breakpoints:{768:{slidesPerView:4,},1200:{slidesPerView:5},}});});}});})(jQuery);